import { DCC_NETWORK_GOAL_DEFAULTS } from '@/lib/network-builder/field-map'
import type { NetworkReadinessRunSummary } from '@/lib/network-builder/types'

export type GenerateReportOptions = {
  summary: NetworkReadinessRunSummary
  missingFieldCounts?: Record<string, number>
  readinessThreshold?: number
}

/** Strategic DCC Network Readiness operating report (markdown). */
export function generateDccNetworkReport(options: GenerateReportOptions): string {
  const { summary, missingFieldCounts = {}, readinessThreshold = DCC_NETWORK_GOAL_DEFAULTS.readinessThreshold } =
    options
  const {
    artistTargetMvp,
    totalContactsStretch12Mo,
    goalId,
  } = DCC_NETWORK_GOAL_DEFAULTS

  const readinessPct =
    summary.totalContacts > 0
      ? Math.round((summary.networkReadyCount / summary.totalContacts) * 100)
      : 0

  const artistProgressPct = Math.round(
    (summary.networkReadyArtistCount / artistTargetMvp) * 100
  )
  const totalProgressPct = Math.round((summary.totalContacts / totalContactsStretch12Mo) * 100)

  const lines: string[] = [
    `# DCC Network Readiness Report`,
    ``,
    `**Week of:** ${new Date(summary.runAt).toLocaleDateString('en-US', { timeZone: 'America/New_York' })}`,
    `**Org:** ${summary.orgSlug}`,
    `**Goal:** ${goalId} (target ${readinessThreshold}% network-ready)`,
    `**Source:** ${summary.source}`,
    summary.runId ? `**Run ID:** ${summary.runId}` : '',
    ``,
    `---`,
    ``,
    `## 1. Network Health`,
    ``,
    `| Metric | Value |`,
    `|--------|------:|`,
    `| Total contacts | ${summary.totalContacts} |`,
    `| Network-ready | ${summary.networkReadyCount} (${readinessPct}%) |`,
    `| Incomplete | ${summary.incompleteCount} |`,
    `| Stale relationships | ${summary.staleCount} |`,
    `| High-priority follow-ups | ${summary.highPriorityCount} |`,
    ``,
    `## 2. Artist Growth Progress`,
    ``,
    `| Target | Current | Progress |`,
    `|--------|--------:|---------:|`,
    `| ${artistTargetMvp} network-ready artists (MVP) | ${summary.networkReadyArtistCount} | ${artistProgressPct}% |`,
    `| ${summary.artistSegmentCount} artist/creator/tech segment | — | — |`,
    `| ${totalContactsStretch12Mo} total contacts (12-mo stretch) | ${summary.totalContacts} | ${totalProgressPct}% |`,
    ``,
    `> **MVP proof target:** ${artistTargetMvp} network-ready artists before scaling outreach volume.`,
    ``,
  ]

  const gapEntries = Object.entries(missingFieldCounts).sort((a, b) => b[1] - a[1])
  if (gapEntries.length) {
    lines.push(`## 3. Top Missing Fields`, ``)
    for (const [field, count] of gapEntries.slice(0, 10)) {
      lines.push(`- **${field}:** ${count} contacts`)
    }
    lines.push(``)
  }

  lines.push(`## 4. Recommended Actions (${summary.proposedActions.length})`, ``)
  for (const action of summary.proposedActions.slice(0, 20)) {
    lines.push(
      `- **[${action.actionType}]** ${action.contactName} (${action.readinessPercent}% ready) — ${action.reason}`
    )
  }
  lines.push(``)

  if (summary.topIncomplete.length) {
    lines.push(`## 5. Top Incomplete Profiles`, ``)
    for (const s of summary.topIncomplete.slice(0, 10)) {
      lines.push(
        `- **${s.fullName}** — ${s.percentReady}% (${s.readinessStatus}) — missing: ${s.missingFields.slice(0, 4).join(', ') || 'none'}`
      )
    }
    lines.push(``)
  }

  if (summary.airtableWrite) {
    lines.push(
      `## 6. Airtable Agent Approvals`,
      ``,
      `- Written: ${summary.airtableWrite.written}`,
      `- Skipped (fixture): ${summary.airtableWrite.skipped}`,
      summary.airtableWrite.errors.length
        ? `- Errors: ${summary.airtableWrite.errors.join('; ')}`
        : `- Errors: none`,
      ``
    )
  }

  lines.push(
    `---`,
    ``,
    `*Generated by DCC Network Builder. Phase 1: dry-run and Airtable approval queue only — no email send.*`
  )

  return lines.filter((l) => l !== undefined).join('\n')
}
