import type { GlossaryTerm } from './types'

/**
 * Master course glossary (A–Z). Pedagogical chapter pointers use `usedInChapters`
 * where we have mapped them; many tool terms ship without chapter pins.
 */
export const VCN_GLOSSARY_TERMS: GlossaryTerm[] = [
  {
    slug: 'anti-interface',
    term: 'Anti-interface',
    type: 'art-term',
    shortDefinition: 'An interface that resists clarity, ease, or predictability on purpose.',
    related: ['interface', 'glitch'],
    usedInChapters: [4],
  },
  {
    slug: 'appropriation',
    term: 'Appropriation',
    type: 'art-term',
    shortDefinition: 'Reusing existing cultural material in a deliberate artistic context.',
    related: ['remix', 'internet-vernacular'],
    usedInChapters: [6],
  },
  {
    slug: 'artifact',
    term: 'Artifact',
    type: 'course-term',
    shortDefinition: 'A concrete output made during class, such as a webpage, prompt, linked story, or final site.',
    usedInChapters: [0, 11],
  },
  {
    slug: 'avatar',
    term: 'Avatar',
    type: 'art-term',
    shortDefinition: 'A digital persona or virtual identity that may or may not point back to a stable offline self.',
    related: ['networked-self'],
    usedInChapters: [7],
  },
  {
    slug: 'branch',
    term: 'Branch',
    type: 'coding-term',
    shortDefinition: 'A separate version of a project used to test changes without altering the main version.',
    related: ['versioning', 'repository'],
    usedInChapters: [0, 9],
  },
  {
    slug: 'browser',
    term: 'Browser',
    type: 'browser-term',
    shortDefinition: 'The software environment where webpages are viewed and experienced.',
    related: ['browser-as-medium', 'viewport'],
    usedInChapters: [2],
  },
  {
    slug: 'browser-as-medium',
    term: 'Browser as medium',
    type: 'course-term',
    shortDefinition:
      'The idea that the browser is not just a container for content, but part of the artwork’s structure and meaning.',
    related: ['net-art', 'viewport', 'page-as-space'],
    usedInChapters: [1, 2],
  },
  {
    slug: 'canon',
    term: 'Canon',
    type: 'art-term',
    shortDefinition: 'A recognized set of artists, works, and references that help define a field.',
    usedInChapters: [1],
  },
  {
    slug: 'claude',
    term: 'Claude',
    type: 'platform-tool',
    shortDefinition: 'An AI assistant useful for planning, explanation, writing, and creative coding support.',
    usedInChapters: [0],
  },
  {
    slug: 'codex',
    term: 'Codex',
    type: 'platform-tool',
    shortDefinition: 'An AI coding agent or coding assistant workflow used for writing, editing, and reviewing code.',
    usedInChapters: [0],
  },
  {
    slug: 'codepen',
    term: 'CodePen',
    type: 'platform-tool',
    shortDefinition: 'A browser-based environment for quickly building and previewing HTML, CSS, and JavaScript experiments.',
    related: ['frontend'],
    usedInChapters: [0, 10],
    sourceNote: 'See CodePen documentation for embeds and exports.',
  },
  {
    slug: 'commit',
    term: 'Commit',
    type: 'coding-term',
    shortDefinition: 'A saved checkpoint in a project’s version history.',
    related: ['repository', 'versioning'],
    usedInChapters: [0, 9],
    sourceNote: 'See GitHub Docs: About commits.',
  },
  {
    slug: 'clone',
    term: 'Clone',
    type: 'coding-term',
    shortDefinition: 'To copy a repository from a remote (such as GitHub) to your local machine so you can edit files and commit changes.',
    related: ['repository', 'commit', 'branch'],
    usedInChapters: [0],
    sourceNote: 'See GitHub Docs on cloning a repository.',
  },
  {
    slug: 'context-window',
    term: 'Context window',
    type: 'course-term',
    shortDefinition:
      'How much surrounding text or code an AI model can consider at once; it shapes what you should paste or point the tool at.',
    related: ['prompt', 'vibecoding'],
    usedInChapters: [0],
  },
  {
    slug: 'cursor-ide',
    term: 'Cursor',
    type: 'platform-tool',
    shortDefinition: 'An AI-first coding editor that helps explain, edit, and navigate codebases.',
    related: ['vscode', 'codex'],
    usedInChapters: [0],
  },
  {
    slug: 'deploy',
    term: 'Deploy',
    type: 'coding-term',
    shortDefinition: 'To make a site or application live on the web.',
    related: ['publishing', 'github-pages'],
    usedInChapters: [9, 11],
  },
  {
    slug: 'digital-trace',
    term: 'Digital trace',
    type: 'course-term',
    shortDefinition: 'The residue of online activity left behind by platforms, devices, and media.',
    related: ['networked-self', 'feed'],
    usedInChapters: [7],
  },
  {
    slug: 'documentation',
    term: 'Documentation',
    type: 'art-term',
    shortDefinition: 'Evidence of a work, such as screenshots, recordings, descriptions, or installation views.',
    related: ['liveness', 'publishing'],
    usedInChapters: [9, 11],
  },
  {
    slug: 'feed',
    term: 'Feed',
    type: 'browser-term',
    shortDefinition: 'A continuously updating stream of platform content.',
    related: ['platform-aesthetics', 'internet-vernacular'],
    usedInChapters: [6],
  },
  {
    slug: 'frontend',
    term: 'Frontend',
    type: 'coding-term',
    shortDefinition: 'The visible layer of a project that users see and interact with.',
    related: ['browser', 'react'],
    usedInChapters: [0, 2],
  },
  {
    slug: 'github',
    term: 'GitHub',
    type: 'platform-tool',
    shortDefinition: 'A platform for storing projects, version history, and repositories.',
    related: ['repository', 'github-pages'],
    usedInChapters: [0, 9],
    sourceNote: 'See GitHub Docs.',
  },
  {
    slug: 'github-pages',
    term: 'GitHub Pages',
    type: 'platform-tool',
    shortDefinition: 'A static hosting workflow that publishes websites directly from a repository.',
    related: ['deploy', 'publishing'],
    usedInChapters: [0, 9, 11],
    sourceNote: 'See GitHub Docs: GitHub Pages.',
  },
  {
    slug: 'glitch',
    term: 'Glitch',
    type: 'art-term',
    shortDefinition: 'A break, distortion, instability, or misbehavior that can become expressive artistic material.',
    related: ['anti-interface', 'legibility'],
    usedInChapters: [4],
  },
  {
    slug: 'hover',
    term: 'Hover',
    type: 'browser-term',
    shortDefinition: 'A state change triggered when a pointer moves over an element.',
    related: ['interaction', 'responsive-behavior'],
    usedInChapters: [5, 10],
    sourceNote: 'See MDN: :hover and touch/accessibility notes.',
  },
  {
    slug: 'hypertext',
    term: 'Hypertext',
    type: 'art-term',
    shortDefinition: 'Writing or structure that unfolds through links, jumps, fragments, or branching paths.',
    related: ['link-as-structure', 'net-art', 'fragment', 'nonlinear-narrative'],
    usedInChapters: [3],
  },
  {
    slug: 'fragment',
    term: 'Fragment',
    type: 'art-term',
    shortDefinition: 'A small piece of text, image, or page division that carries meaning through what it withholds or suggests.',
    related: ['hypertext', 'link-as-structure'],
    usedInChapters: [3],
  },
  {
    slug: 'nonlinear-narrative',
    term: 'Nonlinear narrative',
    type: 'art-term',
    shortDefinition: 'A story structure where sequence is not fixed; the viewer’s path through pages or frames shapes the experience.',
    related: ['hypertext', 'link-as-structure'],
    usedInChapters: [3],
  },
  {
    slug: 'ide',
    term: 'IDE',
    type: 'coding-term',
    shortDefinition: 'A digital workspace where you open files, edit code, inspect folders, and work on projects.',
    related: ['vscode', 'cursor-ide'],
    usedInChapters: [0],
  },
  {
    slug: 'interaction',
    term: 'Interaction',
    type: 'course-term',
    shortDefinition: 'A meaningful change triggered by viewer action.',
    related: ['interface', 'hover'],
    usedInChapters: [5, 10],
  },
  {
    slug: 'infrastructure',
    term: 'Infrastructure',
    type: 'course-term',
    shortDefinition:
      'The channels, hosts, permissions, and institutions that let information move—and shape who can access it.',
    related: ['system', 'systems-as-subject', 'publishing'],
    usedInChapters: [8, 9],
  },
  {
    slug: 'interface',
    term: 'Interface',
    type: 'browser-term',
    shortDefinition: 'The visible system of interaction between a person and a digital environment.',
    related: ['anti-interface', 'legibility'],
    usedInChapters: [4, 5],
  },
  {
    slug: 'legibility',
    term: 'Legibility',
    type: 'course-term',
    shortDefinition: 'How easily a viewer can parse structure, hierarchy, and meaning on a surface.',
    related: ['interface', 'anti-interface', 'glitch'],
    usedInChapters: [4],
  },
  {
    slug: 'internet-vernacular',
    term: 'Internet vernacular',
    type: 'course-term',
    shortDefinition: 'The informal visual and behavioral language of everyday online life.',
    related: ['remix', 'platform-aesthetics', 'net-art'],
    usedInChapters: [6],
  },
  {
    slug: 'liveness',
    term: 'Liveness',
    type: 'course-term',
    shortDefinition: 'The condition of a work existing as an active web encounter rather than only as documentation.',
    related: ['net-art', 'publishing'],
    usedInChapters: [1, 9],
  },
  {
    slug: 'link-as-structure',
    term: 'Link as structure',
    type: 'course-term',
    shortDefinition: 'The idea that hyperlinks do more than navigate; they shape sequence, pacing, and meaning.',
    related: ['hypertext'],
    usedInChapters: [3],
  },
  {
    slug: 'motion',
    term: 'Motion',
    type: 'art-term',
    shortDefinition: 'Visual change over time.',
    related: ['interaction', 'liveness'],
    usedInChapters: [5],
  },
  {
    slug: 'net-art',
    term: 'Net art',
    type: 'art-term',
    shortDefinition: 'Art made for, through, or with the internet and its structures.',
    related: ['browser-as-medium', 'liveness'],
    usedInChapters: [1],
  },
  {
    slug: 'networked-self',
    term: 'Networked self',
    type: 'course-term',
    shortDefinition: 'A self that exists through platforms, devices, interactions, and digital traces.',
    related: ['avatar', 'digital-trace'],
    usedInChapters: [7, 8],
  },
  {
    slug: 'page-as-space',
    term: 'Page as space',
    type: 'course-term',
    shortDefinition: 'The idea that a webpage is not just a document but a compositional environment.',
    related: ['browser-as-medium'],
    usedInChapters: [2],
  },
  {
    slug: 'platform-aesthetics',
    term: 'Platform aesthetics',
    type: 'course-term',
    shortDefinition: 'The recognizable visual and behavioral language encouraged by a specific platform.',
    related: ['internet-vernacular', 'feed'],
    usedInChapters: [6],
  },
  {
    slug: 'prompt',
    term: 'Prompt',
    type: 'course-term',
    shortDefinition: 'A written instruction given to an AI tool.',
    related: ['vibecoding', 'claude', 'codex', 'context-window'],
    usedInChapters: [0],
  },
  {
    slug: 'publishing',
    term: 'Publishing',
    type: 'course-term',
    shortDefinition: 'Making a browser-based work available at a real URL.',
    related: ['liveness', 'github-pages', 'deploy'],
    usedInChapters: [9, 11],
  },
  {
    slug: 'react',
    term: 'React',
    type: 'coding-term',
    shortDefinition: 'A component-based JavaScript library for building interfaces.',
    related: ['frontend'],
    sourceNote: 'See React documentation.',
  },
  {
    slug: 'remix',
    term: 'Remix',
    type: 'art-term',
    shortDefinition: 'Transforming existing digital material into a new work.',
    related: ['appropriation', 'internet-vernacular'],
    usedInChapters: [6],
  },
  {
    slug: 'repository',
    term: 'Repo / Repository',
    type: 'coding-term',
    shortDefinition: 'A project container where files and revision history live.',
    related: ['github', 'commit', 'branch'],
    usedInChapters: [0, 9, 11],
    sourceNote: 'See GitHub Docs: About repositories.',
  },
  {
    slug: 'responsive-behavior',
    term: 'Responsive behavior',
    type: 'browser-term',
    shortDefinition: 'A page changing state in relation to action, timing, or context.',
    related: ['hover', 'interaction'],
    usedInChapters: [5, 10],
  },
  {
    slug: 'software-default',
    term: 'Software default',
    type: 'course-term',
    shortDefinition:
      'A preset look, transition, gradient, or template shipped with software—often culturally loaded, not neutral.',
    related: ['platform-aesthetics', 'internet-vernacular', 'remix'],
    usedInChapters: [6],
  },
  {
    slug: 'scroll',
    term: 'Scroll',
    type: 'browser-term',
    shortDefinition: 'Movement through a page’s vertical or horizontal space.',
    related: ['page-as-space', 'motion'],
    usedInChapters: [2, 5],
  },
  {
    slug: 'system',
    term: 'System',
    type: 'course-term',
    shortDefinition: 'A structured set of relationships, rules, or flows.',
    related: ['systems-as-subject', 'infrastructure'],
    usedInChapters: [8],
  },
  {
    slug: 'systems-as-subject',
    term: 'Systems as subject',
    type: 'art-term',
    shortDefinition: 'Treating hidden routes, exchanges, permissions, and infrastructures as artistic material.',
    related: ['system', 'infrastructure'],
    usedInChapters: [8],
  },
  {
    slug: 'hosting',
    term: 'Hosting',
    type: 'coding-term',
    shortDefinition: 'Where files for a site live on a server or static host so visitors can load them at a URL.',
    related: ['publishing', 'github-pages', 'deploy'],
    usedInChapters: [9, 11],
    sourceNote: 'See GitHub Docs: About GitHub Pages.',
  },
  {
    slug: 'url',
    term: 'URL',
    type: 'browser-term',
    shortDefinition: 'The web address that locates a resource; in net art it can be part of the work’s identity.',
    related: ['publishing', 'liveness', 'browser'],
    usedInChapters: [9, 11],
    sourceNote: 'See MDN: URL.',
  },
  {
    slug: 'versioning',
    term: 'Versioning',
    type: 'coding-term',
    shortDefinition: 'The existence of multiple saved states or revisions of a digital work.',
    related: ['commit', 'branch'],
    usedInChapters: [9],
  },
  {
    slug: 'viewport',
    term: 'Viewport',
    type: 'browser-term',
    shortDefinition: 'The visible area of a webpage within the browser window.',
    related: ['browser-as-medium'],
    usedInChapters: [2, 10],
    sourceNote: 'See MDN: Viewport concepts.',
  },
  {
    slug: 'vibecoding',
    term: 'Vibecoding',
    type: 'course-term',
    shortDefinition:
      'A creative workflow that combines prompts, visual intuition, code, testing, revision, and AI-assisted building.',
    related: ['prompt', 'cursor-ide', 'context-window'],
    usedInChapters: [0],
  },
  {
    slug: 'vscode',
    term: 'VS Code',
    type: 'platform-tool',
    shortDefinition: 'A widely used code editor for working with files, folders, and development tools.',
    related: ['ide', 'cursor-ide'],
    usedInChapters: [0, 9],
    sourceNote: 'See Visual Studio Code documentation.',
  },
].sort((a, b) => a.term.localeCompare(b.term))
