import {
  DEFAULT_CLIENT_OWNERSHIP,
  DEFAULT_DOCUMENTATION_RIGHTS,
  type ClientProposal,
} from '@/lib/dcc/fabrication/schema'
import {
  CAROL_ATTACHMENT_OPTIONS,
  CAROL_CLIENT_QUESTIONS,
  CAROL_CONFIRMED_INPUTS,
  CAROL_CREDITS,
  CAROL_DOCUMENTATION_STAGES,
  CAROL_FABRICATION_PATH,
  CAROL_FUTURE_SCOPE_EXCLUDED,
  CAROL_MATERIAL_DIRECTIONS,
  CAROL_METAL_CASTING_NOTE,
  CAROL_OBJECT_ANALYSIS,
  CAROL_PHASE_1_STEPS,
  CAROL_PRIOR_METAL_STUDY,
  CAROL_PRODUCTION_NETWORK,
  CAROL_PROJECT_SUMMARY,
  CAROL_PROJECT_THESIS,
  CAROL_SOURCE_PATHWAYS,
  CAROL_SOURCE_PATHWAY_NOTE,
  CAROL_STATUS_SUBLABEL,
  CAROL_TESTING_FOCUS,
} from '@/lib/dcc/fabrication/proposals/carol-haggiag-content'
import { CAROL_PROPOSAL_MEDIA_SRC } from '@/lib/dcc/fabrication/proposals/carol-haggiag-media'
import { CAROL_QUOTE_LAYERS } from '@/lib/dcc/fabrication/proposals/carol-quote'

export const CAROL_PROPOSAL: ClientProposal = {
  slug: 'carol-haggiag',
  heroKicker: 'DCC-JOB-002 · Prepare + Fabricate',
  heroTitle: 'Lightweight Earring Prototype Study',
  heroDek:
    'A focused first prototype — preserving texture and sculptural character from Carol’s existing brass casts while solving for lightness, mirrored pair geometry, and wearability.',
  job: {
    id: 'dcc-job-002',
    jobNumber: 'DCC-JOB-002',
    slug: 'carol-haggiag',
    clientName: 'Carol Haggiag',
    projectTitle: 'Lightweight Earring Prototype Study',
    serviceType: 'PREPARE_PLUS_FABRICATE',
    status: 'PROTOTYPE_SCOPING',
    prototypeGoal:
      'Preserve texture and character while making a mirrored ~2.5-inch earring form light enough to wear comfortably.',
    prototypeDesignation: 'Phase 1 · Lightweight Earring Prototype Study',
    intendedUse: 'Wearable earring prototype / jewelry study',
    clientSuppliedMaterial: true,
    machineId: 'anycubic-photon-mono-m7-max',
    projectLeadId: 'moises-sanabria',
    fabricationLocation: 'Bakehouse Art Complex / Studio 43',
    paymentStatus: 'not_quoted',
    documentationRights: { ...DEFAULT_DOCUMENTATION_RIGHTS },
    ownership: { ...DEFAULT_CLIENT_OWNERSHIP },
    createdAt: '2026-09-21',
    updatedAt: '2026-09-23',
  },
  sections: [
    { id: 'object', label: 'The object', shortLabel: 'Object' },
    { id: 'prior-material-study', label: 'Prior material study', shortLabel: 'Learned' },
    { id: 'testing', label: 'What we’re testing', shortLabel: 'Testing' },
    { id: 'material-directions', label: 'Material directions', shortLabel: 'Material' },
    { id: 'on-the-body', label: 'On the body', shortLabel: 'Wear' },
    { id: 'connection', label: 'Connection', shortLabel: 'Attach' },
    { id: 'image-to-object', label: 'From object to prototype', shortLabel: 'Source' },
    { id: 'first-study', label: 'Proposed first study', shortLabel: 'Phase 1' },
    { id: 'questions', label: 'Open questions', shortLabel: 'Questions' },
    { id: 'environment', label: 'Prototype environment', shortLabel: 'Environment' },
    { id: 'whats-next', label: 'What could come next', shortLabel: 'Next' },
    { id: 'documentation', label: 'Documentation', shortLabel: 'Docs' },
    { id: 'price', label: 'Price structure', shortLabel: 'Price' },
    { id: 'scope', label: 'Scope', shortLabel: 'Scope' },
    { id: 'approval', label: 'Next step', shortLabel: 'Next step' },
  ],
  media: [
    {
      id: 'C_SOURCE_FRONT',
      filename: 'Carol_source_front.png',
      src: CAROL_PROPOSAL_MEDIA_SRC.C_SOURCE_FRONT,
      alt: 'Internet reference image — sculptural hand/chicken-foot form, front view.',
      badge: 'Visual inspiration',
      caption: 'Internet reference image supplied by Carol — not her original design.',
      aspect: '4/5',
    },
    {
      id: 'C_SOURCE_BACK',
      filename: 'Carol_source_back.png',
      src: CAROL_PROPOSAL_MEDIA_SRC.C_SOURCE_BACK,
      alt: 'Internet reference image — sculptural hand/chicken-foot form, back view.',
      badge: 'Visual inspiration',
      caption: 'Internet reference image supplied by Carol — not her original design.',
      aspect: '4/5',
    },
    {
      id: 'C_METAL_CAST',
      filename: 'carol-haggiag-chicken-fingers-bronze-reference.jpg',
      src: CAROL_PROPOSAL_MEDIA_SRC.C_METAL_CAST,
      alt: 'Two brass cast chicken-foot forms created by Carol, photographed on a blue work surface.',
      badge: 'Client reference',
      caption:
        'Carol’s existing metal casts preserve substantial texture and physical depth, but their weight makes them unsuitable for the earring direction she now wants to explore.',
      aspect: '4/3',
    },
    {
      id: 'C_MATERIAL_DIRECTION',
      filename: '01_material_direction_no_text.png',
      src: CAROL_PROPOSAL_MEDIA_SRC.C_MATERIAL_DIRECTION,
      alt: 'Material direction study comparing lightweight prototype candidates.',
      badge: 'Material direction',
      aspect: '16/9',
    },
    {
      id: 'C_WEARABILITY',
      filename: '02_wearability_scale_legs_down.png',
      src: CAROL_PROPOSAL_MEDIA_SRC.C_WEARABILITY,
      alt: 'Concept wearability scale study with fingers pointing down.',
      badge: 'Concept study',
      caption:
        'Conceptual scale only — fingers point down. Target ~2.5 in / ~63.5 mm to confirm in person.',
      aspect: '16/9',
    },
    {
      id: 'C_ATTACHMENT',
      filename: '03_attachment_options.png',
      src: CAROL_PROPOSAL_MEDIA_SRC.C_ATTACHMENT,
      alt: 'Attachment concept study — hook, jump ring, and integrated options.',
      badge: 'Concept study',
      aspect: '16/9',
    },
    {
      id: 'C_RESIN_WORKFLOW',
      filename: '04_resin_workflow_environment.png',
      src: CAROL_PROPOSAL_MEDIA_SRC.C_RESIN_WORKFLOW,
      alt: 'Illustrative prototype workflow at Bakehouse — not documentary production evidence.',
      badge: 'Illustrative workflow',
      aspect: '16/9',
    },
  ],
  quoteLineItems: CAROL_QUOTE_LAYERS,
  pricing: {
    serviceLabel: 'Phase 1 · Lightweight Earring Prototype Study',
    amountStatus: 'pending',
    materialNote:
      'Prototype material is chosen after object review — resin is one candidate, not a predetermined solution.',
    terms:
      'Scope and fixed price are confirmed after inspecting Carol’s physical brass pieces in person. No fabrication begins before Carol approves a small, clear scope and price.',
    includedAttempts:
      'Optional revision only if Prototype 1 indicates it is worthwhile — not unlimited iteration.',
    reprintNote: 'Additional studies or production paths are separately approved.',
  },
  materialIds: [],
  processSteps: [...CAROL_FABRICATION_PATH],
  scopeIncluded: [
    'In-person review of Carol’s existing brass pieces',
    'Measure, weigh, and document physical reference',
    'Digital capture or preparation — method chosen at object review',
    'Mirrored study geometry at agreed scale',
    'One focused lightweight prototype test',
    'Weight, texture, and wearability evaluation',
    'Carol review with findings record',
    'Optional scoped revision only if Prototype 1 warrants it',
  ],
  scopeExcluded: CAROL_FUTURE_SCOPE_EXCLUDED,
  requiredInputs: CAROL_CLIENT_QUESTIONS.map((q) => q.text),
  approvalNextStep:
    'Bring the existing metal chicken-foot pieces to Studio 43 for an in-person object review. At the meeting we will inspect, measure, weigh, confirm target scale (~2.5 in), evaluate attachment orientation, and determine the simplest digital capture route. Moises will send a small fixed scope and price before any fabrication begins. This page does not collect payment.',
  modules: [
    'HERO',
    'OBJECT',
    'PRIOR_MATERIAL_STUDY',
    'TESTING',
    'MATERIAL_DIRECTIONS',
    'ON_THE_BODY',
    'CONNECTION',
    'IMAGE_TO_OBJECT',
    'FIRST_STUDY',
    'QUESTIONS',
    'ENVIRONMENT',
    'WHATS_NEXT',
    'DOCUMENTATION',
    'PRICE',
    'SCOPE',
    'APPROVAL',
  ],
}

export {
  CAROL_ATTACHMENT_OPTIONS,
  CAROL_CLIENT_QUESTIONS,
  CAROL_CONFIRMED_INPUTS,
  CAROL_CREDITS,
  CAROL_DOCUMENTATION_STAGES,
  CAROL_FABRICATION_PATH,
  CAROL_FUTURE_SCOPE_EXCLUDED,
  CAROL_MATERIAL_DIRECTIONS,
  CAROL_METAL_CASTING_NOTE,
  CAROL_OBJECT_ANALYSIS,
  CAROL_PHASE_1_STEPS,
  CAROL_PRIOR_METAL_STUDY,
  CAROL_PRODUCTION_NETWORK,
  CAROL_PROJECT_SUMMARY,
  CAROL_PROJECT_THESIS,
  CAROL_QUOTE_LAYERS,
  CAROL_SOURCE_PATHWAYS,
  CAROL_SOURCE_PATHWAY_NOTE,
  CAROL_STATUS_SUBLABEL,
  CAROL_TESTING_FOCUS,
}
