import {
  DEFAULT_CLIENT_OWNERSHIP,
  DEFAULT_DOCUMENTATION_RIGHTS,
  type ClientProposal,
} from '@/lib/dcc/fabrication/schema'
import {
  CAROL_ATTACHMENT_OPTIONS,
  CAROL_CLIENT_QUESTIONS,
  CAROL_CREDITS,
  CAROL_DOCUMENTATION_STAGES,
  CAROL_ESSENTIAL_QUESTION,
  CAROL_FABRICATION_PATH,
  CAROL_FUTURE_SCOPE_EXCLUDED,
  CAROL_MATERIAL_DIRECTIONS,
  CAROL_OBJECT_ANALYSIS,
  CAROL_PHASE_1_STEPS,
  CAROL_PRODUCTION_NETWORK,
  CAROL_PROJECT_SUMMARY,
  CAROL_SOURCE_PATHWAYS,
  CAROL_SOURCE_PATHWAY_NOTE,
  CAROL_TESTING_FOCUS,
} from '@/lib/dcc/fabrication/proposals/carol-haggiag-content'
import { CAROL_PROPOSAL_MEDIA_SRC } from '@/lib/dcc/fabrication/proposals/carol-haggiag-media'
import { CAROL_QUOTE_LAYERS } from '@/lib/dcc/fabrication/proposals/carol-quote'

export const CAROL_PROPOSAL: ClientProposal = {
  slug: 'carol-haggiag',
  heroKicker: 'DCC-JOB-002 · Prepare + Fabricate',
  heroTitle: 'Hand Earring Prototype Study',
  heroDek:
    'A prototype development study exploring digital geometry, resin fabrication, scale, and wearability for sculptural hand earrings.',
  job: {
    id: 'dcc-job-002',
    jobNumber: 'DCC-JOB-002',
    slug: 'carol-haggiag',
    clientName: 'Carol Haggiag',
    projectTitle: 'Hand Earring Prototype Study',
    serviceType: 'PREPARE_PLUS_FABRICATE',
    status: 'PROTOTYPE_SCOPING',
    prototypeGoal:
      'Translate sculptural hand forms into a tested physical jewelry prototype.',
    prototypeDesignation: 'Phase 1 · Prototype Development Study',
    intendedUse: 'Wearable earring prototype / jewelry study',
    clientSuppliedMaterial: false,
    machineId: 'anycubic-photon-mono-m7-max',
    projectLeadId: 'moises-sanabria',
    fabricationLocation: 'Bakehouse Art Complex / Studio 43',
    paymentStatus: 'not_quoted',
    documentationRights: { ...DEFAULT_DOCUMENTATION_RIGHTS },
    ownership: { ...DEFAULT_CLIENT_OWNERSHIP },
    createdAt: '2026-09-21',
    updatedAt: '2026-09-23',
  },
  sections: [
    { id: 'object', label: 'The object', shortLabel: 'Object' },
    { id: 'testing', label: 'What we’re testing', shortLabel: 'Testing' },
    { id: 'material-directions', label: 'Material directions', shortLabel: 'Material' },
    { id: 'on-the-body', label: 'On the body', shortLabel: 'Wear' },
    { id: 'connection', label: 'Connection', shortLabel: 'Attach' },
    { id: 'image-to-object', label: 'From image to object', shortLabel: 'Source' },
    { id: 'first-study', label: 'Proposed first study', shortLabel: 'Phase 1' },
    { id: 'questions', label: 'Questions for Carol', shortLabel: 'Questions' },
    { id: 'environment', label: 'Prototype environment', shortLabel: 'Environment' },
    { id: 'whats-next', label: 'What could come next', shortLabel: 'Next' },
    { id: 'documentation', label: 'Documentation', shortLabel: 'Docs' },
    { id: 'price', label: 'Price structure', shortLabel: 'Price' },
    { id: 'scope', label: 'Scope', shortLabel: 'Scope' },
    { id: 'approval', label: 'Next step', shortLabel: 'Next step' },
  ],
  media: [
    {
      id: 'C_SOURCE_FRONT',
      filename: 'Carol_source_front.png',
      src: CAROL_PROPOSAL_MEDIA_SRC.C_SOURCE_FRONT,
      alt: 'Carol Haggiag reference — sculptural hand form, front view.',
      badge: 'Client reference',
      aspect: '4/5',
    },
    {
      id: 'C_SOURCE_BACK',
      filename: 'Carol_source_back.png',
      src: CAROL_PROPOSAL_MEDIA_SRC.C_SOURCE_BACK,
      alt: 'Carol Haggiag reference — sculptural hand form, back view.',
      badge: 'Client reference',
      aspect: '4/5',
    },
    {
      id: 'C_MATERIAL_DIRECTION',
      filename: '01_material_direction_no_text.png',
      src: CAROL_PROPOSAL_MEDIA_SRC.C_MATERIAL_DIRECTION,
      alt: 'Material direction study comparing resin and future metal paths.',
      badge: 'Material direction',
      aspect: '16/9',
    },
    {
      id: 'C_WEARABILITY',
      filename: '02_wearability_scale_legs_down.png',
      src: CAROL_PROPOSAL_MEDIA_SRC.C_WEARABILITY,
      alt: 'Concept wearability scale study with fingers pointing down.',
      badge: 'Concept study',
      caption:
        'Conceptual scale only — fingers point down. Not literal approved dimensions.',
      aspect: '16/9',
    },
    {
      id: 'C_ATTACHMENT',
      filename: '03_attachment_options.png',
      src: CAROL_PROPOSAL_MEDIA_SRC.C_ATTACHMENT,
      alt: 'Attachment concept study — hook, jump ring, and integrated options.',
      badge: 'Concept study',
      aspect: '16/9',
    },
    {
      id: 'C_RESIN_WORKFLOW',
      filename: '04_resin_workflow_environment.png',
      src: CAROL_PROPOSAL_MEDIA_SRC.C_RESIN_WORKFLOW,
      alt: 'Illustrative resin workflow at Bakehouse — not documentary production evidence.',
      badge: 'Illustrative workflow',
      aspect: '16/9',
    },
  ],
  quoteLineItems: CAROL_QUOTE_LAYERS,
  pricing: {
    serviceLabel: 'Phase 1 · Prototype Development Study',
    amountStatus: 'pending',
    materialNote:
      'Prototype resin and any optional FDM material are scoped separately once geometry and study goals are confirmed.',
    terms:
      'Scope and fixed price are confirmed after reviewing the available digital source and agreeing on the first prototype goal.',
    includedAttempts: 'One defined revision after first physical review — not unlimited iteration.',
    reprintNote: 'Additional studies or production paths are separately approved.',
  },
  materialIds: [],
  processSteps: [...CAROL_FABRICATION_PATH],
  scopeIncluded: [
    'Source review — file, physical object, or images',
    'Digital preparation or reconstruction to study fidelity',
    'Optional FDM scale study if it answers silhouette questions',
    'One high-detail resin test when geometry is ready',
    'Wearability and attachment review checkpoint',
    'Carol review with findings record',
    'One defined revision after review',
  ],
  scopeExcluded: CAROL_FUTURE_SCOPE_EXCLUDED,
  requiredInputs: CAROL_CLIENT_QUESTIONS.map((q) => q.text),
  approvalNextStep:
    'Review this study page, answer the questions (copy and send to Moises), then schedule a source review to lock Phase 1 scope and quote. This page does not collect payment.',
  modules: [
    'HERO',
    'OBJECT',
    'TESTING',
    'MATERIAL_DIRECTIONS',
    'ON_THE_BODY',
    'CONNECTION',
    'IMAGE_TO_OBJECT',
    'FIRST_STUDY',
    'QUESTIONS',
    'ENVIRONMENT',
    'WHATS_NEXT',
    'DOCUMENTATION',
    'PRICE',
    'SCOPE',
    'APPROVAL',
  ],
}

export {
  CAROL_ATTACHMENT_OPTIONS,
  CAROL_CREDITS,
  CAROL_CLIENT_QUESTIONS,
  CAROL_DOCUMENTATION_STAGES,
  CAROL_ESSENTIAL_QUESTION,
  CAROL_FABRICATION_PATH,
  CAROL_FUTURE_SCOPE_EXCLUDED,
  CAROL_MATERIAL_DIRECTIONS,
  CAROL_OBJECT_ANALYSIS,
  CAROL_PHASE_1_STEPS,
  CAROL_PRODUCTION_NETWORK,
  CAROL_PROJECT_SUMMARY,
  CAROL_SOURCE_PATHWAYS,
  CAROL_SOURCE_PATHWAY_NOTE,
  CAROL_TESTING_FOCUS,
  CAROL_QUOTE_LAYERS,
}
