import {
  DEFAULT_CLIENT_OWNERSHIP,
  DEFAULT_DOCUMENTATION_RIGHTS,
  type ClientProposal,
} from '@/lib/dcc/fabrication/schema'

export const CAROL_PROPOSAL: ClientProposal = {
  slug: 'carol-haggiag',
  heroKicker: 'DCC-JOB-002 · Prepare + Fabricate',
  heroTitle: 'Jewelry / ear-cuff prototype',
  heroDek:
    'A prepare-and-fabricate path from reference and intention toward a wearable prototype. Scope and price are not locked on this page yet.',
  job: {
    id: 'dcc-job-002',
    jobNumber: 'DCC-JOB-002',
    slug: 'carol-haggiag',
    clientName: 'Carol Haggiag',
    projectTitle: 'Jewelry / ear-cuff prototype',
    serviceType: 'PREPARE_PLUS_FABRICATE',
    status: 'INQUIRY',
    prototypeGoal: 'Wearable jewelry / ear-cuff prototype from reference and design intention.',
    intendedUse: 'Wearable prototype',
    clientSuppliedMaterial: false,
    projectLeadId: 'moises-sanabria',
    fabricationLocation: 'Studio 43 / Bakehouse Art Complex',
    paymentStatus: 'not_quoted',
    documentationRights: { ...DEFAULT_DOCUMENTATION_RIGHTS },
    ownership: { ...DEFAULT_CLIENT_OWNERSHIP },
    createdAt: '2026-09-21',
    updatedAt: '2026-09-21',
  },
  media: [],
  pricing: {
    serviceLabel: 'Prepare + Fabricate — Prototype 1',
    amountStatus: 'pending',
    materialNote:
      'Prototype material and any later production material are not confirmed on this page.',
    terms: 'Payment terms will be written once scope is quoted.',
    includedAttempts: 'To be scoped.',
    reprintNote: 'Revision and reprint path to be agreed after Prototype 1.',
  },
  materialIds: [],
  processSteps: [
    'REFERENCE / IDEA',
    'DESIGN REVIEW',
    'CAD / MODELING',
    'PROTOTYPE PLAN',
    'FABRICATION',
    'REVIEW',
    'REVISION',
    'NEXT PROTOTYPE',
  ],
  scopeIncluded: [
    'Design-intention review',
    'Reference gathering',
    'CAD / modeling path to be scoped after review',
    'Prototype plan',
  ],
  scopeExcluded: [
    'A quoted fabrication fee (not yet set)',
    'Final production material (path only, not a commitment)',
    'Unlimited revisions',
    'Public case study or public use of project images',
  ],
  requiredInputs: [
    'References (sketches, photos, existing jewelry, fit notes)',
    'Wearability / ear-cuff constraints',
    'Whether this prototype is a form study, a fit study, or both',
  ],
  approvalNextStep:
    'This is a proposal shell. Reply with references and fit notes so DCC can write a scoped quote. This page does not collect payment.',
  modules: [
    'HERO',
    'DESIGN_INTENTION',
    'REFERENCES',
    'REFERENCE_TO_CAD',
    'WEARABILITY_FIT',
    'PROTOTYPE_MATERIAL',
    'FABRICATION',
    'FINAL_MATERIAL_PATH',
    'SCOPE',
    'PRICE',
    'REVISION_PATH',
    'APPROVAL',
  ],
}
