import {
  DEFAULT_CLIENT_OWNERSHIP,
  DEFAULT_DOCUMENTATION_RIGHTS,
  type ClientProposal,
} from '@/lib/dcc/fabrication/schema'
import { HEATHER_PROPOSAL_MEDIA_SRC } from '@/lib/dcc/fabrication/proposals/heather-deitch-media'
import {
  HEATHER_CLIENT_MATERIAL_OUTLAY_USD,
  HEATHER_COST_LINE_ITEMS,
  HEATHER_DEFAULT_FOUNDER_HOURS,
  HEATHER_QUOTE_LINE_ITEMS,
  HEATHER_QUOTE_TOTAL_USD,
} from '@/lib/dcc/fabrication/proposals/heather-quote'

export const HEATHER_PROPOSAL: ClientProposal = {
  slug: 'heather-deitch',
  heroKicker: 'DCC-JOB-001 · Fabricate My File',
  heroTitle: 'Translucent Lighting Prototype',
  heroDek:
    'Prototype 1 for manufacturer review — a scoped fabrication service to turn the current lighting file into a physical translucent part.',
  job: {
    id: 'dcc-job-001',
    jobNumber: 'DCC-JOB-001',
    slug: 'heather-deitch',
    clientName: 'Heather Deitch',
    projectTitle: 'Translucent Lighting Prototype',
    serviceType: 'FABRICATE_MY_FILE',
    status: 'MATERIAL_CONFIRMATION',
    sourceFileVersion: '01_sol_light_mini_3D_print_8-18-2026.pm7m',
    prototypeGoal: 'Manufacturer review of a translucent lighting prototype.',
    prototypeDesignation: 'Prototype 1 — Manufacturer Review',
    prototypeVersion: '1',
    quantity: 1,
    intendedUse: 'Lighting prototype / manufacturer review',
    materialId: 'resin-high-clear-anycubic',
    clientSuppliedMaterial: true,
    machineId: 'anycubic-photon-mono-m7-max',
    projectLeadId: 'moises-sanabria',
    fabricationLocation: 'Studio 43 / Bakehouse Art Complex',
    estimatedResinMl: 646,
    estimatedMachineMinutes: 354,
    quoteAmount: HEATHER_QUOTE_TOTAL_USD,
    depositAmount: 312.5,
    balanceAmount: 312.5,
    paymentStatus: 'deposit_due',
    reprintPolicy:
      'One production attempt is included. Reprints are separately approved.',
    documentationRights: { ...DEFAULT_DOCUMENTATION_RIGHTS },
    ownership: { ...DEFAULT_CLIENT_OWNERSHIP },
    createdAt: '2026-09-21',
    updatedAt: '2026-09-21',
  },
  media: [
    {
      id: 'H_RENDER_001',
      filename: 'H_RENDER_001_hero_translucent_prototype.png',
      src: HEATHER_PROPOSAL_MEDIA_SRC.H_RENDER_001,
      alt: 'Hero render of the translucent lighting prototype.',
      aspect: '21/9',
    },
    {
      id: 'H_RENDER_002',
      filename: 'H_RENDER_002_multiview_translucent_prototype.png',
      src: HEATHER_PROPOSAL_MEDIA_SRC.H_RENDER_002,
      alt: 'Multiview render of the translucent lighting prototype.',
      aspect: '16/9',
    },
    {
      id: 'H_RENDER_003',
      filename: 'H_RENDER_003_supported_production_state.png',
      src: HEATHER_PROPOSAL_MEDIA_SRC.H_RENDER_003,
      alt: 'Supported production-state preview of the current file.',
      aspect: '16/9',
    },
    {
      id: 'H_DIAG_001',
      filename: 'H_DIAG_001_translucency_spectrum.png',
      src: HEATHER_PROPOSAL_MEDIA_SRC.H_DIAG_001,
      alt: 'Diagram of translucency considerations for the lighting part.',
      aspect: '16/9',
    },
    {
      id: 'H_DIAG_002',
      filename: 'H_DIAG_002_fabrication_workflow.png',
      alt: 'Fabrication workflow for Prototype 1.',
      src: HEATHER_PROPOSAL_MEDIA_SRC.H_DIAG_002,
      aspect: '16/9',
    },
    {
      id: 'H_DIAG_003',
      filename: 'H_DIAG_003_finishing_checkpoint.png',
      src: HEATHER_PROPOSAL_MEDIA_SRC.H_DIAG_003,
      alt: 'Finishing checkpoint for support removal and surface review.',
      aspect: '16/9',
    },
    {
      id: 'H_SRC_003',
      filename: 'H_SRC_003_slicer_preview.png',
      src: HEATHER_PROPOSAL_MEDIA_SRC.H_SRC_003,
      alt: 'Baseline slicer preview. Not a final production approval.',
      caption:
        'Baseline slice only. Final material profile and production estimate will be confirmed after resin approval.',
      aspect: '16/9',
    },
  ],
  pricing: {
    serviceLabel: 'Prototype 1 Fabrication Service',
    amountUsd: HEATHER_QUOTE_TOTAL_USD,
    amountStatus: 'quoted',
    materialNote:
      'Resin is purchased directly by Heather after DCC approval. Material cost is not included in the fabrication service fee.',
    terms: '50% deposit / 50% before pickup.',
    includedAttempts: 'One production attempt included.',
    reprintNote: 'Reprints separately approved.',
  },
  quoteLineItems: HEATHER_QUOTE_LINE_ITEMS,
  costLineItems: HEATHER_COST_LINE_ITEMS,
  defaultFounderHours: HEATHER_DEFAULT_FOUNDER_HOURS,
  clientMaterialOutlayUsd: HEATHER_CLIENT_MATERIAL_OUTLAY_USD,
  materialIds: ['resin-high-clear-anycubic'],
  processSteps: [
    'INQUIRY',
    'FILE RECEIVED',
    'TECHNICAL REVIEW',
    'MATERIAL CONFIRMED',
    'SCOPED',
    'QUOTED',
    'ACCEPTED / PAID',
    'OPEN FOR FABRICATION',
    'PRODUCTION',
    'POST-PROCESS',
    'QA',
    'DELIVERY',
    'DOCUMENTED',
  ],
  scopeIncluded: [
    'Technical validation of the current file',
    'Material recommendation and approval checkpoint',
    'Orientation / support review against the existing supported file',
    'Slicing with a confirmed translucent profile after resin approval',
    'One fabrication attempt on the approved machine',
    'Post-processing to the agreed finishing checkpoint',
    'QA against fit and lighting-hardware notes once those inputs arrive',
    'Handoff for manufacturer review',
  ],
  scopeExcluded: [
    'CAD / design changes to the source geometry',
    'Resin purchase (client-supplied after DCC approval)',
    'Lighting hardware, drivers, or electrical assembly',
    'Additional production attempts or reprints',
    'Exhibition finishing beyond the Prototype 1 checkpoint',
    'Public case study or public use of project images',
  ],
  requiredInputs: [
    'Approved translucent resin (product, supplier, bottle) after DCC review',
    'Lighting hardware / fit references (lamp, LED, enclosure, critical dimensions)',
    'Confirmation of Prototype 1 goal: manufacturer review',
    'Deposit to open fabrication after material confirmation',
  ],
  approvalNextStep:
    'Confirm material, send lighting-hardware fit notes, then reply to accept Prototype 1. Deposit is arranged offline — this page does not collect payment.',
  modules: [
    'HERO',
    'PROJECT_GOAL',
    'CURRENT_FILE',
    'MATERIAL_LIGHT',
    'LIGHTING_HARDWARE_FIT',
    'PRODUCTION_WORKFLOW',
    'FINISHING_CHECKPOINT',
    'SCOPE',
    'MANUFACTURER_HANDOFF',
    'PROTOTYPE_2',
    'PRICE_PAYMENT',
    'REQUIRED_INPUTS',
    'APPROVAL',
  ],
}

export const HEATHER_BASELINE_SLICE = {
  file: '01_sol_light_mini_3D_print_8-18-2026.pm7m',
  printer: 'Anycubic Photon Mono M7 Max',
  layerHeightMm: 0.05,
  layers: 3537,
  estimatedResinMl: 646,
  estimatedMassG: 775,
  estimatedHours: 5.9,
  supports: 'already present',
  caveat:
    'Final material profile and production estimate will be confirmed after resin approval.',
} as const

export const HEATHER_LIGHTING_HARDWARE = {
  status: 'awaiting client input',
  body: 'Prototype 1 needs lighting-hardware and fit notes before production lock: intended lamp or LED, enclosure or mount, and any critical dimensions or keep-out surfaces. These are not assumed from the file alone.',
} as const
