/**
 * Airtable field API names for the DCC CRM base.
 * Adjust to match your base; values are defaults from the CRM graph spec.
 */
export const CRM_GRAPH_FIELD_MAP = {
  people: {
    name: 'Full Name',
    titleRole: 'Title / Role',
    institution: 'Institution',
    contactCategory: 'Contact Category',
    warmth: 'Warmth',
    miami: 'Miami Area?',
    city: 'City',
    campaigns: 'Campaigns',
    interactions: 'Interactions',
    graphLayer: 'Graph Layer',
    publicProfileConsent: 'Public Profile Consent',
    demoReadiness: 'Demo Readiness',
    publicNodeSummary: 'Public Node Summary',
    imagePortraitUrl: 'Image / Portrait URL',
    practiceTags: 'Practice Tags',
    interestTags: 'Interest Tags',
    website: 'Website',
    consentStatus: 'Consent Status',
    dccSignupStatus: 'DCC Signup Status',
    researchParticipationStatus: 'Research Participation Status',
    researchAccessLevel: 'Research Access Level',
  },
  seedCandidates: {
    candidateName: 'Candidate Name',
    roleType: 'Role Type',
    institutionSource: 'Institution / Source',
    sourceUrl: 'Source URL',
    website: 'Website',
    city: 'City',
    suggestedPracticeTags: 'Suggested Practice Tags',
    suggestedInterestTags: 'Suggested Interest Tags',
    reviewStatus: 'Review Status',
    recommendedBucket: 'Recommended Bucket',
    constituentLabel: 'Constituent Label',
    contextLinks: 'Context Links',
    miamiConnectionType: 'Miami Connection Type',
    nodePriority: 'Node Priority',
    graphLayer: 'Graph Layer',
    demoReadiness: 'Demo Readiness',
    publicNodeSummary: 'Public Node Summary',
    imagePortraitUrl: 'Image / Portrait URL',
    seedFitScore: 'Seed Fit Score',
    confidence: 'Confidence',
    addToPeople: 'Add to People?',
    relatedCampaign: 'Related Campaign',
  },
  institutions: {
    name: 'Institution Name',
    type: 'Type',
    city: 'City',
    status: 'Status',
    relationshipStrength: 'Relationship Strength',
    miami: 'Miami Area?',
    people: 'People',
    opportunities: 'Opportunities',
    interactions: 'Interactions',
    campaigns: 'Campaigns',
  },
  opportunities: {
    name: 'Opportunity Name',
    institution: 'Institution / Organization',
    peopleInvolved: 'People Involved',
    status: 'Status',
    stage: 'Stage',
    bucket: 'Opportunity Bucket',
    deadline: 'Deadline',
    campaigns: 'Campaigns',
  },
  interactions: {
    date: 'Date',
    type: 'Type',
    institution: 'Institution',
    people: 'People',
    relatedOpportunity: 'Related Opportunity',
  },
  campaigns: {
    name: 'Campaign Name',
    type: 'Campaign Type',
    people: 'Related People',
    institutions: 'Related Institutions',
    opportunities: 'Related Opportunities',
    status: 'Status',
  },
} as const

export type CrmFieldMap = typeof CRM_GRAPH_FIELD_MAP
